/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myaccountant;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static myaccountant.Login.conn;
import static myaccountant.Login.user_type;
import static myaccountant.Login.username;

/**
 *
 * @author vasil
 */
public class Oxima extends javax.swing.JFrame {

    /**
     * Creates new form Oxima
     */
    public Oxima() {
        initComponents();
        load_Ox();
    }  

     private void load_Ox()
    {
        String query = "";
        
        switch (user_type) 
        {
            case "epixeirisi":
                query = "SELECT oxima.ox_onoma, oxima.pinakida, oxima.kostos_telon, oxima.katastasi FROM oxima LEFT JOIN epixeirisi ON oxima.ox_username_pelati = epixeirisi.username_epixeirisis WHERE epixeirisi.username_epixeirisis IS NULL";
                break;
            case "idiotis":
                query = "SELECT oxima.ox_onoma, oxima.pinakida, oxima.kostos_telon, oxima.katastasi FROM oxima LEFT JOIN idiotis ON oxima.ox_username_pelati = idiotis.username_idioti WHERE idiotis.username_idioti IS NULL";
                break;
            default:
                break;
        }

        try 
        {
            PreparedStatement pst = conn.prepareStatement(query);
            
            
            
            ResultSet rs = pst.executeQuery();
            
            DefaultTableModel tblModel = (DefaultTableModel) jTable3.getModel();
            
            tblModel.setRowCount(0); 
            
            while(rs.next())
            {
                String onoma = rs.getString("ox_onoma");
                String eponimo = rs.getString("pinakida");
                String kostos = rs.getString("kostos_telon");
                String katastasi = String.valueOf(rs.getString("katstasi"));
          
                String tbData[] = {onoma , eponimo, kostos, katastasi};
          
                tblModel.addRow(tbData); 
            }
        }
        catch (SQLException e) 
        {
            JOptionPane.showMessageDialog(this, "Error loading data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } 
    }
     
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jButton10 = new javax.swing.JButton();
        jButton11 = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        jTable3 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setText("Προβολή Οχημάτων");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jButton8.setBackground(new java.awt.Color(255, 0, 0));
        jButton8.setText("Επιστροφή");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(0, 204, 255));
        jButton9.setText("Αίτημα Αλλαγής Κατάστασης Οχήματος");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        jButton10.setBackground(new java.awt.Color(0, 204, 255));
        jButton10.setText("Αίτημα Ενημέρωσης Οχήματος");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        jButton11.setBackground(new java.awt.Color(0, 204, 255));
        jButton11.setText("Αίτημα Βεβαίωσης μη Οφειλής Τελών");
        jButton11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton11ActionPerformed(evt);
            }
        });

        jTable3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable3.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Όνομα Οχήματος", "Πινακίδα", "Ονοματεπώνυμο", "Κατάσταση Οχήματος", "Τέλη"
            }
        ));
        jScrollPane5.setViewportView(jTable3);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(9, 9, 9)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jButton10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jButton11, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(14, 14, 14))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(174, 174, 174))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(34, 34, 34)
                        .addComponent(jButton10, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton11, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
      if(user_type.equals("epixeirisi"))
        {
            this.dispose();
            
            Epixeirisi epixeirisi = new Epixeirisi();
            //center the window
            epixeirisi.setLocationRelativeTo(null);
            // Show the login window
            epixeirisi.setVisible(true);
        }
        else
        {
            this.dispose();
            
            Idiotis idiotis = new Idiotis();
            //center the window
            idiotis.setLocationRelativeTo(null);
            // Show the login window
            idiotis.setVisible(true);
}
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
       int selectedRowIndex = jTable3.getSelectedRow();
        
        if (selectedRowIndex == -1) 
        {
            JOptionPane.showMessageDialog(this, "Δεν έχετε επιλέξει Όχημα!", "Error", JOptionPane.ERROR_MESSAGE);
            
            return;
        }

        DefaultTableModel tmodel1 = (DefaultTableModel) jTable3.getModel();
              
        String pinakida = tmodel1.getValueAt(selectedRowIndex, 2).toString();
        String username_pelati = username;
        String eidos_aitimatos = "AITIMA ALLAGIS KATASTASIS";
        
        String checkQuery = "SELECT username_pelati FROM aitima WHERE ait_username_pelati = ? AND eidos = ?";
        
        try 
        {
            PreparedStatement checkStmt = conn.prepareStatement(checkQuery);
            
            checkStmt.setString(1, pinakida);
            checkStmt.setString(2, eidos_aitimatos);
            
            ResultSet rs = checkStmt.executeQuery();
            
            if (rs.next()) 
            {
                JOptionPane.showMessageDialog(this, "Έχετε ήδη κάνει αίτημα για λογιστή!", "Error", JOptionPane.ERROR_MESSAGE);
                return; 
            }
        } 
        catch (SQLException e) 
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Σφάλμα κατά τον έλεγχο των αιτημάτων: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String query = "INSERT INTO aitima VALUES (NULL, ?, ?, DEFAULT, NULL, ?)";
 
        try 
        {
            PreparedStatement pstmt = conn.prepareStatement(query);
            
            pstmt.setString(1, username_pelati);
            pstmt.setString(2, eidos_aitimatos);
            pstmt.setString(3, pinakida);
            
            pstmt.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Το αίτημα στάλθηκε!", "Update", JOptionPane.INFORMATION_MESSAGE);
        } 
        catch (SQLException e) 
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Σφάλμα κατά την εισαγωγή στη βάση δεδομένων: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
                                         
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed
 int selectedRowIndex = jTable3.getSelectedRow();
        
        if (selectedRowIndex == -1) 
        {
            JOptionPane.showMessageDialog(this, "Δεν έχετε επιλέξει Όχημα!", "Error", JOptionPane.ERROR_MESSAGE);
            
            return;
        }

        DefaultTableModel tmodel1 = (DefaultTableModel) jTable3.getModel();
              
        String pinakida = tmodel1.getValueAt(selectedRowIndex, 2).toString();
        String username_pelati = username;
        String eidos_aitimatos = "AITIMA ENIMEROSIS OXIMATON";
        
        String checkQuery = "SELECT username_pelati FROM aitima WHERE ait_username_pelati = ? AND eidos = ?";
        
        try 
        {
            PreparedStatement checkStmt = conn.prepareStatement(checkQuery);
            
            checkStmt.setString(1, pinakida);
            checkStmt.setString(2, eidos_aitimatos);
            
            ResultSet rs = checkStmt.executeQuery();
            
            if (rs.next()) 
            {
                JOptionPane.showMessageDialog(this, "Έχετε ήδη κάνει αίτημα για λογιστή!", "Error", JOptionPane.ERROR_MESSAGE);
                return; 
            }
        } 
        catch (SQLException e) 
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Σφάλμα κατά τον έλεγχο των αιτημάτων: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String query = "INSERT INTO aitima VALUES (NULL, ?, ?, DEFAULT, NULL, ?)";
 
        try 
        {
            PreparedStatement pstmt = conn.prepareStatement(query);
            
            pstmt.setString(1, username_pelati);
            pstmt.setString(2, eidos_aitimatos);
            pstmt.setString(3, pinakida);
            
            pstmt.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Το αίτημα στάλθηκε!", "Update", JOptionPane.INFORMATION_MESSAGE);
        } 
        catch (SQLException e) 
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Σφάλμα κατά την εισαγωγή στη βάση δεδομένων: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
                                              }//GEN-LAST:event_jButton10ActionPerformed

    private void jButton11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton11ActionPerformed
int selectedRowIndex = jTable3.getSelectedRow();
        
        if (selectedRowIndex == -1) 
        {
            JOptionPane.showMessageDialog(this, "Δεν έχετε επιλέξει Όχημα!", "Error", JOptionPane.ERROR_MESSAGE);
            
            return;
        }

        DefaultTableModel tmodel1 = (DefaultTableModel) jTable3.getModel();
              
        String pinakida = tmodel1.getValueAt(selectedRowIndex, 2).toString();
        String username_pelati = username;
        String eidos_aitimatos = "AITIMA BEBAIOSIS MI OFEILIS TELON";
        
        String checkQuery = "SELECT username_pelati FROM aitima WHERE ait_username_pelati = ? AND eidos = ?";
        
        try 
        {
            PreparedStatement checkStmt = conn.prepareStatement(checkQuery);
            
            checkStmt.setString(1, pinakida);
            checkStmt.setString(2, eidos_aitimatos);
            
            ResultSet rs = checkStmt.executeQuery();
            
            if (rs.next()) 
            {
                JOptionPane.showMessageDialog(this, "Έχετε ήδη κάνει αίτημα για λογιστή!", "Error", JOptionPane.ERROR_MESSAGE);
                return; 
            }
        } 
        catch (SQLException e) 
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Σφάλμα κατά τον έλεγχο των αιτημάτων: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        String query = "INSERT INTO aitima VALUES (NULL, ?, ?, DEFAULT, NULL, ?)";
 
        try 
        {
            PreparedStatement pstmt = conn.prepareStatement(query);
            
            pstmt.setString(1, username_pelati);
            pstmt.setString(2, eidos_aitimatos);
            pstmt.setString(3, pinakida);
            
            pstmt.executeUpdate();
            
            JOptionPane.showMessageDialog(this, "Το αίτημα στάλθηκε!", "Update", JOptionPane.INFORMATION_MESSAGE);
        } 
        catch (SQLException e) 
        {
            e.printStackTrace();
            JOptionPane.showMessageDialog(this, "Σφάλμα κατά την εισαγωγή στη βάση δεδομένων: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        }
                                                }//GEN-LAST:event_jButton11ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Oxima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Oxima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Oxima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Oxima.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Oxima().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton11;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTable jTable3;
    // End of variables declaration//GEN-END:variables
}
