/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package myaccountant;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import static myaccountant.Login.*;


/**
 *
 * @author antsa
 */
public class Provoli_Ofeilon extends javax.swing.JFrame {

    /**
     * Creates new form Provoli_Ofeilon
     */
    public Provoli_Ofeilon() {
        initComponents();
        load_Ofeiles();
    }
    
    private void load_Ofeiles()
    {
        String query = "";
        query = "SELECT ofeili_id, ofeili_poso FROM ofeili WHERE ofeili_username_pelati = ?";

        try 
        {
            PreparedStatement pst = conn.prepareStatement(query);
            
            pst.setString(1, username); 
            
            ResultSet rs = pst.executeQuery();
            
            DefaultTableModel tblModel = (DefaultTableModel) jTable1.getModel();
            
            tblModel.setRowCount(0); 
            
            while(rs.next())
            {
                String id = rs.getString("ofeili_id");
                String poso = rs.getString("ofeili_poso");
          
                String tbData[] = {id , poso};
          
                tblModel.addRow(tbData); 
            }
        }
        
        catch (SQLException e) 
        {
            JOptionPane.showMessageDialog(this, "Σφάλμα ανάκτησης δεδομένων: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } 
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setBackground(new java.awt.Color(51, 51, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 0, 36)); // NOI18N
        jLabel1.setText("Προβολή Οφειλών");
        jLabel1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id Οφειλής", "Ποσό Οφειλής"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jButton8.setBackground(new java.awt.Color(0, 204, 255));
        jButton8.setText("Αίτημα Ενημέρωσης Οφειλών");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setBackground(new java.awt.Color(255, 0, 0));
        jButton9.setText("Επιστροφή");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 217, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(120, 120, 120)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(229, 229, 229)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(162, 162, 162)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 429, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(156, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 239, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        int response = JOptionPane.showConfirmDialog(this, "Θέλετε σίγουρα να στείλετε Αίτημα Ενημέρωσης Οφειλών?", "Confirm", JOptionPane.YES_NO_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(response == JOptionPane.YES_OPTION) {
            switch (user_type) 
            {
                case "epixeirisi":
                String getlogistiEp = "SELECT epix_username_logisti FROM epixeirisi WHERE username_epixeirisis = ?";
            
                String uname_logistiEp = null;
        
                try 
                {
                    PreparedStatement checkStmt = conn.prepareStatement(getlogistiEp);
            
                    checkStmt.setString(1, username);
            
                    ResultSet rs = checkStmt.executeQuery();
            
                    if (rs.next()) 
                    {
                        uname_logistiEp = rs.getString("epix_username_logisti");
                    }
                } 
            
                catch (SQLException e) 
                {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Σφάλμα κατά την ανάκτηση δεδομένων: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                String username_epix = username;
                String eidos_aitimatos_epix = "AITIMA ENIMEROSIS OFEILIS";
                int poso_epix = 30;
                
                String query = "INSERT INTO aitima VALUES (NULL, ?, ?, ?, NULL, ?)";
 
            try 
            {
                PreparedStatement pstmt = conn.prepareStatement(query);
            
                pstmt.setString(1, username_epix);
                pstmt.setString(2, eidos_aitimatos_epix);
                pstmt.setInt(3, poso_epix);
                pstmt.setString(4, uname_logistiEp);
            
                pstmt.executeUpdate();
            
                JOptionPane.showMessageDialog(this, "Το αίτημα στάλθηκε!", "Update", JOptionPane.INFORMATION_MESSAGE);
            } 
            catch (SQLException e) 
            {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Σφάλμα κατά την εισαγωγή στη βάση δεδομένων: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
                break;
                
                case "idiotis":
                    
                String getlogistiIdioti = "SELECT idiotis_username_logisti FROM idiotis WHERE username_idioti = ?";
            
                String uname_logistiIdioti = null;
        
                try 
                {
                    PreparedStatement checkStmt = conn.prepareStatement(getlogistiIdioti);
            
                    checkStmt.setString(1, username);
            
                    ResultSet rs = checkStmt.executeQuery();
            
                    if (rs.next()) 
                    {
                        uname_logistiIdioti = rs.getString("idiotis_username_logisti");
                    }
                } 
            
                catch (SQLException e) 
                {
                    e.printStackTrace();
                    JOptionPane.showMessageDialog(this, "Σφάλμα κατά την ανάκτηση δεδομένων: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
                    return;
                }
                
                String username_id = username;
                String eidos_aitimatos_id = "AITIMA ENIMEROSIS OFEILIS";
                int poso_idioti = 30;
                
                String query1 = "INSERT INTO aitima VALUES (NULL, ?, ?, ?, NULL, ?)";
 
            try 
            {
                PreparedStatement pstmt = conn.prepareStatement(query1);
            
                pstmt.setString(1, username_id);
                pstmt.setString(2, eidos_aitimatos_id);
                pstmt.setInt(3, poso_idioti);
                pstmt.setString(4, uname_logistiIdioti);
            
                pstmt.executeUpdate();
            
                JOptionPane.showMessageDialog(this, "Το αίτημα στάλθηκε!", "Update", JOptionPane.INFORMATION_MESSAGE);
            } 
            catch (SQLException e) 
            {
                e.printStackTrace();
                JOptionPane.showMessageDialog(this, "Σφάλμα κατά την εισαγωγή στη βάση δεδομένων: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
            }
                
                break;
                default:
                break;
            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
                if(user_type.equals("epixeirisi"))
        {
            this.dispose();
            
            Epixeirisi epixeirisi = new Epixeirisi();
            //center the window
            epixeirisi.setLocationRelativeTo(null);
            // Show the login window
            epixeirisi.setVisible(true);
        }
        else
        {
            this.dispose();
            
            Idiotis idiotis = new Idiotis();
            //center the window
            idiotis.setLocationRelativeTo(null);
            // Show the login window
            idiotis.setVisible(true);
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Provoli_Ofeilon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Provoli_Ofeilon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Provoli_Ofeilon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Provoli_Ofeilon.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Provoli_Ofeilon().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
